general = {
  name = "Gigawatt";
  interpolation = "auto";
  output_backend = "pa";
  ignore_volume_control = "yes";
  drift_tolerance_in_seconds = 0.012;
  resync_threshold_in_seconds = 0.150;
  audio_backend_buffer_desired_length_in_seconds = 0.50;
  audio_backend_buffer_interpolation_threshold_in_seconds = 0.075;
  port = 5000;
};
sessioncontrol = {
  allow_session_interruption = "yes";
  session_timeout = 120;
};
metadata = {
  enabled = "yes";
  include_cover_art = "no";
  pipe_name = "/tmp/gigawatt-airplay.meta";
  pipe_timeout = 5000;
};
pa = {
  application_name = "Gigawatt AirPlay";
};
