general = {
  name = "Gigawatt";
  interpolation = "basic";
  output_backend = "pa";
  ignore_volume_control = "no";
  port = 5000;
  resync_threshold_in_seconds = 0.0;
  audio_backend_buffer_desired_length_in_seconds = 0.35;
  audio_backend_latency_offset_in_seconds = -0.45;
};
sessioncontrol = {
  allow_session_interruption = "yes";
  session_timeout = 120;
};
metadata = {
  enabled = "yes";
  include_cover_art = "no";
  pipe_name = "/tmp/gigawatt-airplay.meta";
  pipe_timeout = 5000;
};
pa = {
  application_name = "Gigawatt AirPlay";
  server = "/var/run/pulse/native";
  sink = "alsa_output.platform-sound-spdif.stereo-fallback";
};
